sudo: false
language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install tox
    - pip install tox-travis
    - pip install python-coveralls
    - pip install pyqt5
    - sudo apt-get install python-dev libudev-dev libusb-1.0-0-dev
script:
    - tox
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install pycurl requests && contrib/make_locale; fi
    - coveralls
